#! /bin/sh

#chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Hibernate\n  Log Out\n  Lock" | rofi -dmenu -i -theme-str '@import "power.rasi"')
chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Log Out\n  Lock" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"  Lock") pidof hyprlock || hyprlock -q ;;
	"  Suspend") pidof hyprlock || hyprlock -q & systemctl suspend ;;
	"  Power Off") systemctl poweroff ;;
	"  Restart") systemctl reboot ;;
# 	"  Hibernate") systemctl hibernate ;;
	"  Log Out") hyprctl dispatch exit 0 ;;
	*) exit 1 ;;
esac
