export ZSH="$HOME/.oh-my-zsh"

# Set theme to gentoo
ZSH_THEME="gentoo"

# update automatically without asking
zstyle ':omz:update' mode auto
zstyle ':omz:update' verbose minimal

plugins=(git nvm npm docker debian zsh-autosuggestions command-not-found)

# source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# PNPM Aliases, everyone makes mistakes
alias ppnm=pnpm
alias pmnp=pnpm
alias pnmp=pnpm
alias pmpn=pnpm
alias pnpp=pnpm
alias pmpm=pnpm
alias pnnm=pnpm
alias pnpmn=pnpm
alias pnm=pnpm
alias pmp=pnpm
alias pnml=pnpm
alias pnmu=pnpm
alias pnnp=pnpm
alias pnbm=pnpm
alias pnb=pnpm
alias pnbu=pnpm
alias pnbm=pnpm

# alias for fastfetch (neofetch alternative)
alias neofetch="fastfetch"

# deno
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Git GPG Key
export GPG_TTY=$(tty)

# corepack
export COREPACK_ENABLE_STRICT=0


# Fix $PATH
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# gh-cli completions
eval $(gh completion --shell zsh)

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Configure atuin
eval "$(atuin init zsh)"
. "$HOME/.atuin/bin/env"


# Add console-ninja to path [Visual Studio Code Extension]
PATH=~/.console-ninja/.bin:$PATH
export PATH=$HOME/.local/bin:$PATH
